// <auto-generated />
using System;
using Hero_WebAPI_EFCore.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hero_WebAPI_EFCore.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230919232656_Secret_HeroId_Nullable")]
    partial class Secret_HeroId_Nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.Hero", b =>
                {
                    b.Property<int>("HeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("HeroId");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.HeroMovie", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("HeroId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("HeroesMovies");
                });

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.Secret", b =>
                {
                    b.Property<int>("SecretId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("HeroId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("SecretId");

                    b.HasIndex("HeroId")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("WeaponId");

                    b.HasIndex("HeroId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.HeroMovie", b =>
                {
                    b.HasOne("Hero_WebAPI_EFCore.Domain.Models.Hero", "Hero")
                        .WithMany("HeroesMovies")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hero_WebAPI_EFCore.Domain.Models.Movie", "Movie")
                        .WithMany("HeroesMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.Secret", b =>
                {
                    b.HasOne("Hero_WebAPI_EFCore.Domain.Models.Hero", "Hero")
                        .WithOne("Secret")
                        .HasForeignKey("Hero_WebAPI_EFCore.Domain.Models.Secret", "HeroId");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.Weapon", b =>
                {
                    b.HasOne("Hero_WebAPI_EFCore.Domain.Models.Hero", "Hero")
                        .WithMany("Weapons")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.Hero", b =>
                {
                    b.Navigation("HeroesMovies");

                    b.Navigation("Secret");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("Hero_WebAPI_EFCore.Domain.Models.Movie", b =>
                {
                    b.Navigation("HeroesMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
